[package]
name = "register-description-tools"
version = "0.1.0"
authors = ["Juuso Tuononen <jutuon@outlook.com>"]
edition = "2018"
publish = false

[dependencies]
clap = "2.33.0"
cursive = "0.12"
toml = { version = "0.5", features = ["preserve_order"] }
